### ISSUE TITLE
MySQL 8 support 

### ISSUE THREAD

**Issue by sujith3g** [bitronix/btm#100]
I'm getting the following error(`XAER_RMERR: Fatal error`) when trying to connect to MySQL 8 using `btm-2.1.3.jar`. 
Is btm support MySQL 8?

```
com.mysql.cj.jdbc.MysqlXAException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
        at com.mysql.cj.jdbc.MysqlXAConnection.mapXAExceptionFromSQLException(MysqlXAConnection.java:344)
        at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:189)
        at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:117)
        at bitronix.tm.recovery.RecoveryHelper.recover(RecoveryHelper.java:103)
        at bitronix.tm.recovery.RecoveryHelper.recover(RecoveryHelper.java:61)
        at bitronix.tm.recovery.Recoverer.recover(Recoverer.java:259)
        at bitronix.tm.recovery.Recoverer.recoverAllResources(Recoverer.java:226)
        at bitronix.tm.recovery.Recoverer.run(Recoverer.java:142)
        at bitronix.tm.BitronixTransactionManager.<init>(BitronixTransactionManager.java:87)
        at bitronix.tm.TransactionManagerServices.getTransactionManager(TransactionManagerServices.java:75)
        at MySQLConnectionExample.main(MySQLConnectionExample.java:22)
Caused by: java.sql.SQLException: XAER_RMERR: Fatal error occurred in the transaction branch - check your data for consistency
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1218)
        at com.mysql.cj.jdbc.MysqlXAConnection.recover(MysqlXAConnection.java:168)
        ... 9 more

Feb 26, 2019 11:06:24 AM bitronix.tm.recovery.Recoverer run
I
```

**Comment by lorban** [comment]
Looks like this problem to me: https://jira.percona.com/browse/PS-4800
