### ISSUE TITLE
TransactionLogAppender's FileChannel is closed on interrupt and never reopened

### ISSUE THREAD

**Issue by tbilles** [bitronix/btm#45]
When an interrupt happens on a thread during writing the transaction log, the underlying FileChannel is closed as a result. Any further use will throw a java.nio.channels.ClosedChannelException rendering the transaction manager unusable since the transaction logs are never reopened. The main issue here is that no other threads can use it any more.

Are there any solutions to situations like this?

```
Caused by: org.hibernate.TransactionException: JTA commit failed: 
        at org.hibernate.engine.transaction.internal.jta.JtaTransaction.doCommit(JtaTransaction.java:157) ~[hibernate-core.jar:4.3.8.Final]
        at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:180) ~[hibernate-core.jar:4.3.8.Final]
        ... 19 common frames omitted
Caused by: bitronix.tm.internal.BitronixSystemException: error logging status
        at bitronix.tm.BitronixTransaction.setStatus(BitronixTransaction.java:409) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.BitronixTransaction.setStatus(BitronixTransaction.java:387) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.twopc.Preparer.prepare(Preparer.java:64) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.BitronixTransaction.commit(BitronixTransaction.java:281) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.BitronixTransactionManager.commit(BitronixTransactionManager.java:183) ~[btm.jar:3.0.0-SNAPSHOT]
        at org.hibernate.engine.transaction.internal.jta.JtaTransaction.doCommit(JtaTransaction.java:152) ~[hibernate-core.jar:4.3.8.Final]
        ... 20 common frames omitted
Caused by: java.nio.channels.ClosedChannelException: null
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:99) ~[na:1.7.0_51]
        at sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:717) ~[na:1.7.0_51]
        at bitronix.tm.journal.TransactionLogHeader.setPosition(TransactionLogHeader.java:205) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.journal.TransactionLogAppender.writeLog(TransactionLogAppender.java:154) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.journal.DiskJournal.log(DiskJournal.java:144) ~[btm.jar:3.0.0-SNAPSHOT]
        at bitronix.tm.BitronixTransaction.setStatus(BitronixTransaction.java:398) ~[btm.jar:3.0.0-SNAPSHOT]
        ... 25 common frames omitted
```

**Comment by krokodylowy** [comment]
According to old "Multithreaded Programming with JAVA™ Technology" avoid interruption and cancellation if at all possible.
But sometimes we can override Future.cancel(), Therad.interrupt() or SecurityManager methods and do some things in transaction manager before thread exit.
So the question is what we can do before interruption and closed channel occur?
Does TransactionManagerServices.getTransactionManager().rollback(); or something else is correct way to stop permanent fail of transaction log?

**Comment by lorban** [comment]
There is an ugly workaround that would work: when you get such ClosedChannelException - which can be done by checking the root cause of the exception - clearing the interrupt flag then closing and reopening the disk journal will make BTM resume where it left, ie:

```
    try {
      ...
    } catch (org.hibernate.TransactionException e) {
      Throwable rootCause = null;
      while (rootCause != e.getCause()) {
        rootCause = e.getCause();
      }
      if (rootCause instanceof ClosedChannelException) {
        Thread.interrupted(); // clear interrupted flag
        TransactionManagerServices.getJournal().close();
        TransactionManagerServices.getJournal().open();
      }
    }
```

You'll get some error in the logs complaining that the journal couldn't be properly closed but all aborted transactions should be recovered and new ones should start flowing again happily.

This is not ideal, but should safely work around the problem.

**Comment by krokodylowy** [comment]
Thanks. We will try.

**Comment by leofromgroza** [comment]
We had the same issue. @lorban , thank you for the solution.
But as for me it is not an ideal solution. It would be great if some kind of fix can be added into Bitronix code (somewhere into bitronix.tm.journal.DiskJournal or another place).
